apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: worker-app-container
    image: dockersamples/examplevotingapp_worker
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"